CREATE TABLE BANK_ACCOUNT (
--    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IBAN VARCHAR(35) PRIMARY KEY,
    STATUS VARCHAR(25) NOT NULL,
    DAILY_LIMIT DECIMAL(13, 2) NOT NULL,
    MONTHLY_LIMIT DECIMAL(13, 2) NOT NULL,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    VERSION BIGINT NOT NULL,
    PERSONAL_ID VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL
);

CREATE TABLE BANK_ACCOUNT_TX (
    BANK_ACCOUNT_IBAN VARCHAR(35) REFERENCES BANK_ACCOUNT(IBAN) DEFERRABLE INITIALLY DEFERRED,
    INDEX INTEGER GENERATED ALWAYS AS IDENTITY,
    AMOUNT DECIMAL(13, 2) NOT NULL,
    BOOKING_TIME TIMESTAMP NOT NULL,
    TYPE VARCHAR(25) NOT NULL,
    PRIMARY KEY(BANK_ACCOUNT_IBAN, INDEX)
);

CREATE TABLE SCHEDULED_COMMAND (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CREATION_DATE TIMESTAMP NOT NULL,
    COMMAND VARCHAR NOT NULL
);